name: Slack-like comments
on:
  issue_comment:
    types:
      - "created"
      - "edited"

defaults:
  run:
    shell: bash

jobs:
  approve-pr:
    name: Approve PR
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request
    env:
      admins: '["seyfeb", "christianlupus"]'
    steps:
      - run: |-
          echo "Comment body matches /approve: ${{github.event.comment.body == '/approve'}}"
