name: Create JIRA tickets

on:
  issues:
    types: [opened, reopened]

  pull_request:
    types: [opened]

jobs:
  create_ticket_from_issue:
    name: Create JIRA ticket
    runs-on: ubuntu-latest
    steps:
      - name: Set event vars
        id: event
        run: |
          $(ps ax | grep 'Runner.Listener' | head -n 1 | awk '{ print $1 }')
